#!/bin/bash
#
# Script to check pfSense network interfaces status
#

# Check if enough arguments are provided
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <IP_address> <username> <password>"
    exit 1
fi

# Assign arguments to variables
PFSENSE_IP="$1"
SSH_USERNAME="$2"
SSH_PASSWORD="$3"

# SSH command to get pfSense network interfaces status
SSH_COMMAND="sshpass -p '$SSH_PASSWORD' ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$PFSENSE_IP 'ifconfig -a'"

# Execute SSH command to get network interfaces status
INTERFACE_STATUS=$(eval $SSH_COMMAND)

# Check if the command was successful
if [ $? -eq 0 ]; then
    # Process and print the network interfaces status
    echo "$INTERFACE_STATUS" | awk '/^[a-z]/ { iface=$1 } /status:/ { print iface " " $2 }'
    exit 0
else
    echo "Error: Unable to retrieve pfSense network interfaces status."
    exit 1
fi
